### ISSUE TITLE
Leader board Structure

### ISSUE THREAD

**Issue by alphathunderwave** [briankarUB/CGames#53] opened 2018-04-04 17:30 UTC
Creating a data structure that saves a 'username' and score from the assignments and displays them in order sorting by score. The leaderboard is updated each time a user passes a lesson. each user only can complete each lesson once for a score.

**Comment by briankarUB** [comment] 2018-04-04 18:26
Maybe a duplicate of #42 and #43

**Closed** 2018-04-13 00:03 UTC
