### ISSUE TITLE
Alpha Testing [bug] LeaderBoard

### ISSUE THREAD

**Issue by kai123456** [briankarUB/CGames#91] opened 2018-04-20 05:45 UTC
After a few time of playing the game and enter the name, sometimes the leaderboard will lead me to a different page with different people's name. And sometimes the name won't register unless I refresh the page and restart the game.

**Comment by briankarUB** [comment] 2018-04-20 05:47
Duplicate of #82

**Closed by briankarUB** 2018-04-20 05:47 UTC
