### ISSUE TITLE
[Alpha testing feedback] Last tutorial has a next button

### ISSUE THREAD

**Issue by ianleshan** [briankarUB/CGames#105] opened 2018-04-20 18:34 UTC
When I reached the last tutorial I saw a next button at the bottom. But when I clicked it, it couldn't find the page. I'm guessing because it was the last one and you might be adding more in the future. You should remove the next button on the last page.

**Comment by briankarUB** [comment] 2018-04-20 18:38
Duplicate of #90

**Closed by briankarUB** 2018-04-20 18:38 UTC
Labels: duplicate
