### ISSUE TITLE
Bug: LeaderBoard

### ISSUE THREAD

**Issue by Manvijay** [briankarUB/CGames#89] opened 2018-04-20 04:56 UTC
Leader Board doesn't show all the scores on one screen.

Elaboration: It's evident that you have put in a lot of efforts in building this very clean project. I just wanted to make you aware of this leader board problem that your users might face later on. So I tried the same quiz 5 times and checked the leader board after that. it showed my first three results but not the last two. I refreshed the page and then it showed me the other two but then it didn't show me the first three. You guys might want to look in this. Good luck!

**Comment by briankarUB** [comment] 2018-04-20 05:14
Duplicate of #82

**Closed by briankarUB** 2018-04-20 05:14 UTC
Labels: duplicate
